name: packer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.1
  flutter_bloc: ^8.0.0
  json_annotation: ^4.4.0
  injectable: ^1.5.0
  get_it: ^7.2.0
  flutter_form_builder: ^7.0.0
  dio: ^4.0.4
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  flutter_barcode_scanner: ^2.0.0
  fluttertoast: ^8.0.8
  freezed_annotation: ^1.1.0
  equatable: ^2.0.3
  loading_indicator: ^3.0.2

dev_dependencies:
  flutter_gen_runner: ^4.1.3
  build_runner: ^2.1.7
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  injectable_generator: ^1.5.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - assets/images
    - assets/env/.env

flutter_intl:
  enabled: true

dependency_overrides:
  intl: 0.17.0

flutter_gen:
  integrations:
    flutter_svg: true